version: "3.9"
services:
  node:
    image: "node:14"
    environment:
      PATH: /app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ./:/app
      - ~/data/kbase:/data
      - node_modules:/app/node_modules
volumes:
  node_modules:
