apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-cache
spec:
  storageClassName: local-path-large
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ${PODNAME}
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: console
      image: node:19
      command: [ /bin/bash ]
      workingDir: /code/web/brain
      stdin: true
      tty: true
      volumeMounts:
        - name: code
          mountPath: /code
        - name: data
          mountPath: /data
        - name: npmcache
          mountPath: /home/node/.npm
  volumes:
    - name: code
      persistentVolumeClaim:
        claimName: homedir-code
    - name: data
      persistentVolumeClaim:
        claimName: homedir-data
    - name: npmcache
      persistentVolumeClaim:
        claimName: npm-cache
