definitions:
  editor:
    propertyNames:
      $ref: "#/definitions/validIdentifier"
    additionalProperties:  
      $ref: "#/definitions/editorNode"
  editorNode:
    type: object
    additionalProperties: false
    allOf: &editorNodeAllOf
      - anyOf:
          - required: [title]
          - required: [text]
          - required: [link]
      - anyOf:
          - required: [title]
          - required: [broader]
          - required: [link]
          - required: [src]
    properties: &editorNodeProperties
      title:
        type: string
        pattern: "^[^/:]+$"
      link:
        type: string
        format: uri
      aka:
        type: array
        uniqueItems: true
        minItems: 1
        items:
          type: string
      stale:
        type: boolean
      links:
        $ref: "#/definitions/linkList"
      src:
        $ref: "#/definitions/src"
      text:
        $ref: "#/definitions/plainText"
      props:
        $ref: "#/definitions/props"
      isA:
        $ref: "#/definitions/namedRefList"
      broader: #skos
        $ref: "#/definitions/namedRefList"
      narrower: #skos
        $ref: "#/definitions/namedRefList"
      collection: #skos:collection/member
        $ref: "#/definitions/namedRefListInput"
      next:
        $ref: "#/definitions/namedRefListInput"
      later:
        $ref: "#/definitions/namedRefListInput"
      related:
        $ref: "#/definitions/namedRefList"
      notes:
        $ref: "#/definitions/namedRefListInput"
      quotes:
        $ref: "#/definitions/namedRefList"
      backrefs:
        $ref: "#/definitions/namedRefList"
  couchDeletion:
    type: object
    required:
      - _id
      - _rev
      - _deleted
    properties:
      _deleted:
        type: boolean
        enum: [true]
      _id:
        type: string
      _rev:
        type: string
  couchDocument:
    type: object
    additionalProperties: false
    allOf: *editorNodeAllOf
    required:
      - _id
      - id
    properties:
      <<: *editorNodeProperties
      _id:
        type: string
      _rev:
        type: string
      id:
        allOf:
          - $ref: "#/definitions/validIdentifier"
      created_at:
        type: number
      stale: false
      stale_at:
        type: number
      broader:
        $ref: "#/definitions/namedRefList"
      narrower:
        $ref: "#/definitions/namedRefList"
      collection:
        $ref: "#/definitions/namedRefList"
      next:
        $ref: "#/definitions/namedRefList"
      later:
        $ref: "#/definitions/namedRefList"
      related:
        $ref: "#/definitions/namedRefList"
      backrefs: false
      quotes: false
      notes: false
    dependencies:
      text: [created_at]
      created_at: [text]
      collection:
        properties:
          narrower: false
          isA: false
      narrower:
        properties:
          collection: false
      isA:
        properties:
          collection: false
  existingDocument:
    allOf:
      - $ref: "#/definitions/couchDocument"
      - required: [_rev]
  couchTopicUpdate:
    oneOf:
      - $ref: "#/definitions/couchDeletion"
      - $ref: "#/definitions/couchDocument"
  stringList:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: "#/definitions/plainText"
  props:
    type: object
    additionalProperties: false
    properties:
      twitter:
        $ref: "#/definitions/plainText"
      quantity:
        $ref: "#/definitions/plainText"
      date:
        type: string
        pattern: "^20\\d{2}-\\d{2}-\\d{2}$"
  src:
    oneOf:
      - type: string
        format: uri
      - $ref: "#/definitions/namedRef"
  linkList:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: "#/definitions/maybeLabeledLink"
  maybeLabeledLink:
    oneOf:
      - $ref: "#/definitions/namedRef"
      - type: string
        format: uri
      - type: object
        additionalProperties: false
        required:
          - search
        properties:
          search:
            type: string
  namedRefListInput:
    type: array
    minItems: 1
    items:
      oneOf:
        - $ref: "#/definitions/editorNode"
        - $ref: "#/definitions/plainText"
        - $ref: "#/definitions/namedRef"
  namedRefList:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: "#/definitions/namedRef"
  namedRef:
    type: object
    required:
      - ref
    additionalProperties: false
    properties:
      label:
        type: string
      ref:
        $ref: "#/definitions/validIdentifier"
  validIdentifier:
    type: string
    pattern: "^[a-zA-Z0-9-.]+$"
    maxLength: 32
  plainText:
    type: string
    allOf:
      - not:
          pattern: '^/'
      - not:
          pattern: 'https?://'
