definitions:
  editor:
    propertyNames:
      type: string
      pattern: "^[a-zA-Z0-9-_.]+$" # validIdentifier
    additionalProperties:  
      $ref: "#/definitions/editorNode"
  editorNode:
    type: object
    additionalProperties: false
    allOf: &editorNodeAllOf
      - anyOf:
          - required: [title]
          - required: [text]
          - required: [link]
      - anyOf:
          - required: [title]
          - required: [related]
    properties: &editorNodeProperties
      title:
        type: string
        pattern: "^[^/:]+$"
      link:
        type: string
        format: uri
      aka:
        type: array
        uniqueItems: true
        minItems: 1
        items:
          type: string
      stale:
        type: boolean
      links:
        $ref: "#/definitions/linkList"
      src:
        $ref: "#/definitions/src"
      text:
        $ref: "#/definitions/plainText"
      props:
        $ref: "#/definitions/props"
      next:
        $ref: "#/definitions/objRefListInput"
      later:
        $ref: "#/definitions/objRefListInput"
      list:
        $ref: "#/definitions/objRefListInput"
      related:
        $ref: "#/definitions/objRefListInput"
      backrefs:
        type: array
        minItems: 1
        items:
          $ref: "#/definitions/objLabeledRef"
      notes:
        $ref: "#/definitions/objRefListInput"
  couchDeletion:
    type: object
    required:
      - _id
      - _rev
      - _deleted
    properties:
      _deleted:
        type: boolean
        enum: [true]
      _id:
        type: string
      _rev:
        type: string
  couchDocument:
    type: object
    additionalProperties: false
    allOf: *editorNodeAllOf
    required:
      - _id
      - id
    properties:
      <<: *editorNodeProperties
      _id:
        type: string
      _rev:
        type: string
      id:
        $ref: "#/definitions/slashRefString"
      created_at:
        type: number
      stale: false
      stale_at:
        type: number
      next:
        $ref: "#/definitions/slashRefList"
      later:
        $ref: "#/definitions/slashRefList"
      list:
        $ref: "#/definitions/slashRefList"
      related:
        $ref: "#/definitions/slashRefList"
      backrefs: false
      notes: false
    dependencies:
      text: [created_at]
      created_at: [text]
  existingDocument:
    allOf:
      - $ref: "#/definitions/couchDocument"
      - required: [_rev]
  couchTopicUpdate:
    oneOf:
      - $ref: "#/definitions/couchDeletion"
      - $ref: "#/definitions/couchDocument"
  objRefStringList:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      oneOf:
        - $ref: "#/definitions/plainText"
        - $ref: "#/definitions/objLabeledRef"
  stringList:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: "#/definitions/plainText"
  props:
    type: object
    additionalProperties:
      oneOf:
        - $ref: "#/definitions/plainText"
        - $ref: "#/definitions/maybeLabeledLink"
        - $ref: "#/definitions/slashRefString"
    properties:
      date:
        type: string
        pattern: "^20\\d{2}-\\d{2}-\\d{2}$"
  src:
    oneOf:
      - $ref: "#/definitions/maybeLabeledLink"
      - $ref: "#/definitions/slashRefString"
      - type: string
        enum: [ibid]
  linkList:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: "#/definitions/maybeLabeledLink"
  maybeLabeledLink:
    oneOf:
      - type: string
        format: uri
      - type: object
        additionalProperties: false
        required:
          - search
        properties:
          search:
            type: string
      - type: object
        additionalProperties: false
        required:
          - link
          - title
        properties:
          link:
            type: string
            format: uri
          title:
            type: string
  objRefListInput:
    type: array
    minItems: 1
    items:
      oneOf:
        - $ref: "#/definitions/editorNode"
        - $ref: "#/definitions/plainText"
        - $ref: "#/definitions/objLabeledRef"
  objRefList:
    type: array
    minItems: 1
    items:
      oneOf:
        - $ref: "#/definitions/objLabeledRef"
        - $ref: "#/definitions/slashRefString"
  objLabeledRef:
    type: object
    required:
      - label
      - ref
    additionalProperties: false
    properties:
      label:
        type: string
      ref:
        $ref: "#/definitions/slashRefString"
  slashRefList:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: "#/definitions/slashRefString"
  slashRefString:
    type: string
    # Ref strings start with a slash
    pattern: "^/[a-zA-Z0-9-_.]+$" # validIdentifier
  plainText:
    type: string
    not:
      pattern: 'https?://'
