definitions:
  payload:
    type: object
    required: [_id,metadata,topic]
    additionalProperties: false
    properties:
      _id:
        type: string
      _rev:
        type: string
      _deleted:
        type: boolean
        enum: [true]
      metadata:
        $ref: "#/definitions/topicMetadata"
      topic:
        $ref: "#/definitions/topic"
  requiredFields:
    allOf:
      - anyOf:
          - required: [title]
          - required: [text]
          - required: [link]
      - anyOf:
          - required: [title]
          - required: [broader]
          - required: [actionOn]
          - required: [link]
          - required: [src]
  topicMetadata:
    type: object
    additionalProperties: false
    required: [id,created_at]
    properties:
      id:
        allOf:
          - $ref: "#/definitions/validIdentifier"
      created_at:
        type: number
        minimum: 1
      stale_at:
        type: number
      nextAction:
        $ref: "#/definitions/namedRef"
      firstAction:
        type: boolean
  topic:
    type: object
    additionalProperties: false
    allOf:
      - $ref: "#/definitions/requiredFields"
    properties: &topicProperties
      title:
        type: string
        pattern: "^[^/:]+$"
      link:
        type: string
        format: uri
      aka:
        type: array
        uniqueItems: true
        minItems: 1
        items:
          type: string
      links:
        type: array
        uniqueItems: true
        minItems: 1
        items:
          oneOf:
            - $ref: "#/definitions/namedRef"
            - type: string
              format: uri
            - type: object
              additionalProperties: false
              required:
                - search
              properties:
                search:
                  type: string
      src:
        oneOf:
          - type: string
            format: uri
          - $ref: "#/definitions/namedRef"
      text:
        $ref: "#/definitions/plainText"
      props:
        type: object
        additionalProperties: false
        properties:
          twitter:
            $ref: "#/definitions/plainText"
          quantity:
            $ref: "#/definitions/plainText"
          date:
            type: string
            pattern: "^20\\d{2}-\\d{2}-\\d{2}$"
      type:
        $ref: "#/definitions/namedRef"
      broader:
        $ref: "#/definitions/namedRefList"
      actionOn:
        allOf:
          - $ref: "#/definitions/namedRefList"
          - maxItems: 1
      narrower:
        $ref: "#/definitions/namedRefList"
      collection:
        $ref: "#/definitions/namedRefList"
      related:
        $ref: "#/definitions/namedRefList"
    dependencies:
      collection:
        properties:
          narrower: false
          type: false
      narrower:
        properties:
          collection: false
      type:
        properties:
          collection: false
  editor:
    propertyNames:
      $ref: "#/definitions/validIdentifier"
    additionalProperties:  
      $ref: "#/definitions/editorNode"
  editorNode:
    type: object
    additionalProperties: false
    allOf:
      - $ref: "#/definitions/requiredFields"
    properties:
      <<: *topicProperties
      stale:
        type: boolean
        enum: [true]
      collection: #skos:collection/member
        $ref: "#/definitions/namedRefListInput"
      notes:
        $ref: "#/definitions/namedRefListInput"
      tasks:
        $ref: "#/definitions/namedRefListInput"
      quotes:
        $ref: "#/definitions/namedRefList"
      backrefs:
        $ref: "#/definitions/namedRefList"
  editorInputNode:
    type: object
    allOf:
      - $ref: "#/definitions/editorNode"
    properties:
      tasks: false
      broader: false
      stale: false
  namedRefListInput:
    type: array
    minItems: 1
    items:
      oneOf:
        - $ref: "#/definitions/editorInputNode"
        - $ref: "#/definitions/plainText"
        - $ref: "#/definitions/namedRef"
  namedRefList:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: "#/definitions/namedRef"
  namedRef:
    type: object
    required:
      - ref
    additionalProperties: false
    properties:
      label:
        type: string
      ref:
        $ref: "#/definitions/validIdentifier"
  validIdentifier:
    type: string
    pattern: "^[a-zA-Z0-9-.]+$"
    maxLength: 32
  plainText:
    type: string
    allOf:
      - not:
          pattern: '^/'
      - not:
          pattern: 'https?://'
